preloads:
  - ${SNPIT_DEFAULT_CONFIG}

system:
  paths:
    scratch_dir: /mnt/roman-science-internal/snpit/users/${LOGNAME}/phrosty_scratch
    temp_dir: /mnt/roman-science-internal/snpit/${LOGNAME}/phrosty_scratch
    dia_out_dir: /mnt/roman-science-internal/snpit/${LOGNAME}/phrosty_dia_out
    ltcv_dir: /mnt/roman-science-internal/snpit/${LOGNAME}/phrosty_lc_out

  db:
    passwordfile: ${HOME}/secrets/roman_snpit_db_ricksim_smdc

photometry:
  phrosty:
    force_sky_subtract: false
    keep_intermediate: false
    remove_temp_dir: false
    kerpolyorder: 2

    sfft:
      radius_cut_detmask: 2

    psf:
      type: gaussian
      params: {'sigmax': 0.43, 'sigmay': 0.43}
