replaceable_preloads:
  - /data/snpit/env/environment_checkout_for_native/smdc_interactive_config.yaml 

system:
  paths:
    scratch_dir: ${system.paths.temp_dir}/phrosty_temp
    dia_out_dir: ${system.paths.dev_storage}/phrosty_dia_out
    ltcv_dir: ${system.paths.dev_storage}/phrosty_lc_out

  db:
    passwordfile: /home/secrets/roman_snpit_db_rknop_dev

photometry:
  phrosty:
    force_sky_subtract: false
    keep_intermediate: false
    remove_temp_dir: false
    kerpolyorder: 2

    sfft:
      radius_cut_detmask: 2

    psf:
      type: gaussian
      params: {'sigmax': 0.43, 'sigmay': 0.43}
